# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node_modules
        run: yarn
      - name: Test – Jest
        run: yarn coverage
        env:
          CI: true
      - name: Test – Eslint, Tslint, Tscheck
        if: ${{ always() && matrix.node-version == '14' }}
        run: yarn lint
      - name: Flow checks
        if: ${{ always() && matrix.node-version == '14' }}
        run: yarn flow
      - name: Publish Test Report
        if: ${{ always() && matrix.node-version == '14' }}
        uses: mikepenz/action-junit-report@127c778ac944abc0f48a5103964304bab7eb208b
        with:
          check_name: JUnit Annotations for Node ${{ matrix.node-version }}
          report_paths: '**/coverage/junit/**/*.xml'

  publish:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/alpha' || github.ref == 'refs/heads/beta'
    needs: [tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install node_modules
        run: yarn install
      - name: Build
        run: yarn build
      - name: Semantic Release (publish to npm)
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
